# Generated by Django 4.1.7 on 2023-04-22 13:56

import django.db.models.deletion
import helpers.validators.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LnxGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        max_length=65,
                        unique=True,
                        validators=[helpers.validators.model_validators.validate_username],
                    ),
                ),
                ("gid_number", models.BigIntegerField(unique=True)),
                ("guidhex", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="LnxShell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "shell",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[helpers.validators.model_validators.validate_path],
                    ),
                ),
                ("built_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LnxUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[helpers.validators.model_validators.validate_username],
                    ),
                ),
                ("uid_number", models.BigIntegerField(unique=True)),
                (
                    "home_dir",
                    models.CharField(
                        max_length=100,
                        validators=[helpers.validators.model_validators.validate_path],
                    ),
                ),
                ("gecos", models.CharField(max_length=64)),
                ("guidhex", models.CharField(max_length=60)),
                (
                    "login_shell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="lnxusers.lnxshell"
                    ),
                ),
                (
                    "primary_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="lnxusers.lnxgroup"
                    ),
                ),
            ],
        ),
    ]
