# Generated by Django 4.1.7 on 2023-02-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lnxuser',
            old_name='gid_number',
            new_name='primary_group',
        ),
    ]
