# Generated by Django 4.1.7 on 2023-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0002_rename_gid_number_lnxuser_primary_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnxgroup',
            name='gid_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lnxshell',
            name='shell',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lnxuser',
            name='uid_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='lnxshell',
            constraint=models.CheckConstraint(check=models.Q(('shell__length__gte', 4)), name='lnxusers_lnxshell_shell_length'),
        ),
    ]
