# Generated by Django 4.1.7 on 2023-02-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0004_alter_lnxshell_shell'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lnxshell',
            name='lnxusers_lnxshell_shell_length',
        ),
    ]
