# Generated by Django 4.1.7 on 2023-02-20 20:11

from django.db import migrations, models
import helpers.validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0005_remove_lnxshell_lnxusers_lnxshell_shell_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnxuser',
            name='home_dir',
            field=models.CharField(max_length=100, validators=[helpers.validators.model_validators.validate_path]),
        ),
        migrations.AlterField(
            model_name='lnxuser',
            name='username',
            field=models.CharField(max_length=50, validators=[helpers.validators.model_validators.validate_username]),
        ),
    ]
