# Generated by Django 4.1.7 on 2023-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0007_alter_lnxgroup_groupname_alter_lnxuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnxuser',
            name='guidhex',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
