# Generated by Django 4.1.7 on 2023-03-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0008_lnxuser_guidhex'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnxgroup',
            name='guidhex',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
