# Generated by Django 4.1.7 on 2023-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0009_lnxgroup_guidhex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnxuser',
            name='login_shell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lnxusers.lnxshell'),
        ),
        migrations.AlterField(
            model_name='lnxuser',
            name='primary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lnxusers.lnxgroup'),
        ),
    ]
