# Generated by Django 4.1.7 on 2023-03-25 21:23

from django.db import migrations, models
import helpers.validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0011_lnxshell_built_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnxgroup',
            name='groupname',
            field=models.CharField(max_length=65, unique=True, validators=[helpers.validators.model_validators.validate_username]),
        ),
    ]
