repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      exclude: cfn
    - id: check-json
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: detect-aws-credentials
      args: ["--allow-missing-credentials"]
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args:
        - --autofix
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.0
  hooks:
    - id: gitleaks
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
    - id: actionlint
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args:
        - --ignore=B907,E203,W503
      additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
