# Generated by Django 4.1.7 on 2023-02-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapconfig', '0002_ldapdn_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='ldap_user',
            field=models.EmailField(max_length=255),
        ),
    ]
