# Generated by Django 4.1.7 on 2023-03-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldapconfig', '0005_poolrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='groups_pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_group_pool_set', to='ldapconfig.poolrange'),
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='users_pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_user_pool_set', to='ldapconfig.poolrange'),
        ),
    ]
