# Generated by Django 4.1.7 on 2023-03-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0007_alter_lnxgroup_groupname_alter_lnxuser_username'),
        ('ldapconfig', '0006_ldapconfig_groups_pool_ldapconfig_users_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='default_group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='defaul_group_set', to='lnxusers.lnxgroup'),
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='default_shell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defaul_shell_set', to='lnxusers.lnxshell'),
        ),
    ]
