# Generated by Django 4.1.7 on 2023-04-22 13:56

from django.db import migrations, models
import django.db.models.deletion
import helpers.validators.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lnxusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudoCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, validators=[helpers.validators.model_validators.validate_path])),
                ('args', models.CharField(blank=True, max_length=255)),
                ('diggest', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SudoCommandRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('commands', models.ManyToManyField(to='sudoers.sudocommand')),
            ],
        ),
        migrations.CreateModel(
            name='SudoHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True, validators=[helpers.validators.model_validators.validate_hostname])),
            ],
        ),
        migrations.CreateModel(
            name='SudoHostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('servers', models.ManyToManyField(to='sudoers.sudohost')),
            ],
        ),
        migrations.CreateModel(
            name='SudoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('guidhex', models.CharField(editable=False, max_length=60)),
                ('sudo_order', models.IntegerField(blank=True, help_text='Note: priority order, bigger values more priority.', null=True)),
                ('sudo_not_before', models.DateField(blank=True, help_text='Note: This is the start date.', null=True)),
                ('sudo_not_after', models.DateField(blank=True, help_text='Note: This is the expiration date.', null=True)),
                ('run_as_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudorule_runasgroup_set', to='lnxusers.lnxgroup')),
                ('run_as_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudorule_runasuser_set', to='lnxusers.lnxuser')),
                ('sudo_command', models.ManyToManyField(to='sudoers.sudocommand')),
                ('sudo_command_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoers.sudocommandrole')),
                ('sudo_host_groups', models.ManyToManyField(to='sudoers.sudohostgroup')),
                ('sudo_host_servers', models.ManyToManyField(to='sudoers.sudohost')),
                ('sudo_user_groups', models.ManyToManyField(to='lnxusers.lnxgroup')),
                ('sudo_user_users', models.ManyToManyField(to='lnxusers.lnxuser')),
            ],
        ),
    ]
