# Generated by Django 4.1.7 on 2023-04-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudorule',
            name='sudo_command_role',
        ),
        migrations.AddField(
            model_name='sudorule',
            name='sudo_command_role',
            field=models.ManyToManyField(to='sudoers.sudocommandrole'),
        ),
    ]
