# Generated by Django 4.1.7 on 2023-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudorule',
            name='name',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
