# Generated by Django 4.1.7 on 2023-02-20 20:11

from django.db import migrations, models
import helpers.validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0003_remove_sudorule_sudo_host_remove_sudorule_sudo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudohost',
            name='hostname',
            field=models.CharField(max_length=253, validators=[helpers.validators.model_validators.validate_hostname]),
        ),
    ]
