# Generated by Django 4.1.7 on 2023-02-20 20:16

from django.db import migrations, models
import helpers.validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0004_alter_sudohost_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudohost',
            name='hostname',
            field=models.CharField(max_length=253, unique=True, validators=[helpers.validators.model_validators.validate_hostname]),
        ),
    ]
