# Generated by Django 4.1.7 on 2023-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoers", "0004_sudohostgroup_guidhex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudohostgroup",
            name="nested",
            field=models.ManyToManyField(blank=True, to="sudoers.sudohostgroup"),
        ),
    ]
