# Generated by Django 4.1.7 on 2023-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoers", "0005_alter_sudohostgroup_nested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudohostgroup",
            name="nested",
            field=models.ManyToManyField(
                blank=True, related_name="parents", to="sudoers.sudohostgroup"
            ),
        ),
    ]
