# Generated by Django 4.2.6 on 2024-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnxusers", "0001_initial"),
        ("sudoers", "0007_alter_sudorule_sudo_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_user_groups",
            field=models.ManyToManyField(blank=True, to="lnxusers.lnxgroup"),
        ),
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_user_users",
            field=models.ManyToManyField(blank=True, to="lnxusers.lnxuser"),
        ),
    ]
