# Generated by Django 5.0.4 on 2024-04-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoers", "0008_alter_sudorule_sudo_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_command",
            field=models.ManyToManyField(blank=True, to="sudoers.sudocommand"),
        ),
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_command_role",
            field=models.ManyToManyField(blank=True, to="sudoers.sudocommandrole"),
        ),
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_host_groups",
            field=models.ManyToManyField(blank=True, to="sudoers.sudohostgroup"),
        ),
        migrations.AlterField(
            model_name="sudorule",
            name="sudo_host_servers",
            field=models.ManyToManyField(blank=True, to="sudoers.sudohost"),
        ),
    ]
