# Generated by Django 4.1.7 on 2023-03-26 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0012_alter_sudorule_sudo_not_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_before',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 14, 18, 38, 821190, tzinfo=datetime.timezone.utc), help_text='Note: This is the start date'),
        ),
    ]
