# Generated by Django 4.1.7 on 2023-03-26 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0013_alter_sudorule_sudo_not_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_before',
            field=models.DateField(default=django.utils.timezone.now, help_text='Note: This is the start date'),
        ),
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_order',
            field=models.IntegerField(default=0, help_text='Note: priority order, bigger values more priority.'),
        ),
    ]
