# Generated by Django 4.1.7 on 2023-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0015_alter_sudorule_sudo_not_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='guidhex',
            field=models.CharField(editable=False, max_length=60),
        ),
    ]
