# Generated by Django 4.1.7 on 2023-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0017_alter_sudorule_sudo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_after',
            field=models.DateField(blank=True, help_text='Note: This is the expiration date.', null=True),
        ),
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_before',
            field=models.DateField(blank=True, help_text='Note: This is the start date.', null=True),
        ),
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_order',
            field=models.IntegerField(blank=True, help_text='Note: priority order, bigger values more priority.', null=True),
        ),
    ]
