# Generated by Django 4.1.7 on 2023-04-22 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.validators.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lnxusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True, validators=[helpers.validators.model_validators.validate_host_ip])),
            ],
        ),
        migrations.CreateModel(
            name='LDAPDn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=255, unique=True, validators=[helpers.validators.model_validators.validate_dn])),
                ('scope', models.CharField(choices=[('OL', 'One Level'), ('SB', 'Subtree')], default='OL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PoolRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_min', models.PositiveBigIntegerField(default=50000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(4294967295)])),
                ('pool_max', models.PositiveBigIntegerField(default=60000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(4294967295)])),
            ],
        ),
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, validators=[helpers.validators.model_validators.validate_hostname])),
                ('ldap_user', models.EmailField(max_length=255)),
                ('krb_auth', models.BooleanField(default=False)),
                ('ldap_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_group_set', to='lnxusers.lnxgroup')),
                ('default_shell', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_shell_set', to='lnxusers.lnxshell')),
                ('dns_hostname', models.ManyToManyField(to='ldapconfig.dnshost')),
                ('group_dn', models.ManyToManyField(related_name='group_ldapconfig_set', to='ldapconfig.ldapdn')),
                ('groups_pool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_group_pool_set', to='ldapconfig.poolrange')),
                ('sudo_dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudo_config_set', to='ldapconfig.ldapdn')),
                ('user_dn', models.ManyToManyField(to='ldapconfig.ldapdn')),
                ('users_pool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_user_pool_set', to='ldapconfig.poolrange')),
            ],
        ),
    ]
