# Generated by Django 4.1.7 on 2023-03-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldapconfig', '0003_alter_ldapconfig_ldap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='sudo_dn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sudo_config_set', to='ldapconfig.ldapdn'),
            preserve_default=False,
        ),
    ]
