# Generated by Django 4.1.7 on 2023-03-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0007_alter_lnxgroup_groupname_alter_lnxuser_username'),
        ('ldapconfig', '0007_ldapconfig_default_group_ldapconfig_default_shell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='default_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defaul_group_set', to='lnxusers.lnxgroup'),
        ),
    ]
