# Generated by Django 4.1.7 on 2023-03-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0009_lnxgroup_guidhex'),
        ('ldapconfig', '0008_alter_ldapconfig_default_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='default_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_group_set', to='lnxusers.lnxgroup'),
        ),
        migrations.AlterField(
            model_name='ldapconfig',
            name='default_shell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_shell_set', to='lnxusers.lnxshell'),
        ),
    ]
