# Generated by Django 4.1.7 on 2023-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0002_sudorule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudorule',
            name='sudo_host',
        ),
        migrations.RemoveField(
            model_name='sudorule',
            name='sudo_user',
        ),
        migrations.AddField(
            model_name='sudorule',
            name='sudo_host',
            field=models.ManyToManyField(to='sudoers.sudohost'),
        ),
        migrations.AddField(
            model_name='sudorule',
            name='sudo_user',
            field=models.ManyToManyField(to='sudoers.sudouser'),
        ),
    ]
