# Generated by Django 4.1.7 on 2023-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0006_sudocommand_args_alter_sudocommand_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudouser',
            name='username',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
