# Generated by Django 4.1.7 on 2023-03-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0008_alter_sudocommand_args_alter_sudorule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudorule',
            name='guidhex',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
