# Generated by Django 4.1.7 on 2023-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0011_sudorule_sudo_not_after_sudorule_sudo_not_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_before',
            field=models.DateField(auto_now_add=True, help_text='Note: This is the start date'),
        ),
    ]
