# Generated by Django 4.1.7 on 2023-03-26 14:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0014_alter_sudorule_sudo_not_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_after',
            field=models.DateField(default=datetime.datetime(9999, 4, 10, 0, 0), help_text='Note: This is the expiration date.'),
        ),
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_not_before',
            field=models.DateField(default=django.utils.timezone.now, help_text='Note: This is the start date.'),
        ),
    ]
