# Generated by Django 4.1.7 on 2023-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoers', '0016_alter_sudorule_guidhex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudorule',
            name='sudo_order',
            field=models.IntegerField(default=0, help_text='Note: priority order, bigger values more priority.', null=True),
        ),
    ]
