# Generated by Django 4.1.7 on 2023-02-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sudoers', '0003_remove_sudorule_sudo_host_remove_sudorule_sudo_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LnxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=65)),
                ('gid_number', models.BigIntegerField()),
                ('related_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoers.sudouser')),
            ],
        ),
        migrations.CreateModel(
            name='LnxShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LnxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('uid_number', models.BigIntegerField()),
                ('home_dir', models.CharField(max_length=100)),
                ('gecos', models.CharField(max_length=64)),
                ('gid_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lnxusers.lnxgroup')),
                ('login_shell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lnxusers.lnxshell')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoers.sudouser')),
            ],
        ),
    ]
