# Generated by Django 4.1.7 on 2023-02-19 19:02

from django.db import migrations, models
import helpers.validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('lnxusers', '0003_alter_lnxgroup_gid_number_alter_lnxshell_shell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnxshell',
            name='shell',
            field=models.CharField(max_length=100, unique=True, validators=[helpers.validators.model_validators.validate_path]),
        ),
    ]
